### ISSUE TITLE
Accessing field BandSummary.band

### ISSUE THREAD

**Issue by samuelkim314** [thchr/MPBUtils.jl#16]
When I print out a BandSummary, I get something like
```julia
julia> summaries[1]
2-band BandSummary:
 bands:      1:2
 n:          A₁, B₁, C₁⁻+C₂⁻, D₁, E₁, -Γ₁⁺+Γ₁⁻+2Γ₂⁻, Y₁⁺+Y₂⁺, Z₂⁺+Z₂⁻
 topology:   nontrivial
 indicators: (0,1) ∈ Z₂×Z₂
```
However, there is a discrepancy as the `bands` field is actually called `band` in the struct, so to access it you have to call:
```julia
julia> summaries[1].band
1:2
```
This is a little confusing. Perhaps the names should be made consistent, or explicit documentation added?

**Comment by thchr** [comment]
Good catch, we should definitely make that consistent. I think the issue stems from having a separate notion of `bands` elsewhere in the `read_utils.jl` file; but that notion should probably be called something like `bandss` (... little bit awkward). A PR to change `.band` to `.bands` would be welcome!
